spring:
  application:
    name: boot
  datasource:
    url: jdbc:postgresql://${DB_URL}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
apis:
  book-catalog:
    base: https://openlibrary.org
  currency:
    base: https://currencyapi.net/api
    key: a5496027130f4776bb4628a0567ff4682937
resilience4j:
  circuitbreaker:
    instances:
      bookCatalog:
        sliding-window-size: 10 # Last requests
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 30
        permitted-number-of-calls-in-half-open-state: 4
        minimum-number-of-calls: 5 # Min amount needed for decision-making
        record-exceptions:
          - org.vitalii.fedyk.bibliotopiabff.infrastructure.common.exception.ExternalServiceException
      currencyExchange:
        sliding-window-size: 10
        minimum-number-of-calls: 4
        failure-rate-threshold: 75
        wait-duration-in-open-state:
          seconds: 180
        permitted-number-of-calls-in-half-open-state: 5
        record-exceptions:
          - org.vitalii.fedyk.bibliotopiabff.infrastructure.common.exception.ExternalServiceException
